// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetUserLogoutNoContentCode is the HTTP code returned for type GetUserLogoutNoContent
const GetUserLogoutNoContentCode int = 204

/*GetUserLogoutNoContent Remove session cookie and redirect to home page.

swagger:response getUserLogoutNoContent
*/
type GetUserLogoutNoContent struct {
}

// NewGetUserLogoutNoContent creates GetUserLogoutNoContent with default headers values
func NewGetUserLogoutNoContent() *GetUserLogoutNoContent {

	return &GetUserLogoutNoContent{}
}

// WriteResponse to the client
func (o *GetUserLogoutNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
