// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"go.timothygu.me/downtomeet/models"
)

// GetHelloOKCode is the HTTP code returned for type GetHelloOK
const GetHelloOKCode int = 200

/*GetHelloOK successful hello world response

swagger:response getHelloOK
*/
type GetHelloOK struct {

	/*
	  In: Body
	*/
	Payload *GetHelloOKBody `json:"body,omitempty"`
}

// NewGetHelloOK creates GetHelloOK with default headers values
func NewGetHelloOK() *GetHelloOK {

	return &GetHelloOK{}
}

// WithPayload adds the payload to the get hello o k response
func (o *GetHelloOK) WithPayload(payload *GetHelloOKBody) *GetHelloOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get hello o k response
func (o *GetHelloOK) SetPayload(payload *GetHelloOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHelloOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetHelloDefault generic error response

swagger:response getHelloDefault
*/
type GetHelloDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetHelloDefault creates GetHelloDefault with default headers values
func NewGetHelloDefault(code int) *GetHelloDefault {
	if code <= 0 {
		code = 500
	}

	return &GetHelloDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get hello default response
func (o *GetHelloDefault) WithStatusCode(code int) *GetHelloDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get hello default response
func (o *GetHelloDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get hello default response
func (o *GetHelloDefault) WithPayload(payload *models.Error) *GetHelloDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get hello default response
func (o *GetHelloDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHelloDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
