// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetUserFacebookRedirectOKCode is the HTTP code returned for type GetUserFacebookRedirectOK
const GetUserFacebookRedirectOKCode int = 200

/*GetUserFacebookRedirectOK Simple HTML file that will redirect user to the home page.

swagger:response getUserFacebookRedirectOK
*/
type GetUserFacebookRedirectOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetUserFacebookRedirectOK creates GetUserFacebookRedirectOK with default headers values
func NewGetUserFacebookRedirectOK() *GetUserFacebookRedirectOK {

	return &GetUserFacebookRedirectOK{}
}

// WithPayload adds the payload to the get user facebook redirect o k response
func (o *GetUserFacebookRedirectOK) WithPayload(payload string) *GetUserFacebookRedirectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user facebook redirect o k response
func (o *GetUserFacebookRedirectOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserFacebookRedirectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetUserFacebookRedirectSeeOtherCode is the HTTP code returned for type GetUserFacebookRedirectSeeOther
const GetUserFacebookRedirectSeeOtherCode int = 303

/*GetUserFacebookRedirectSeeOther Redirect to home page.

swagger:response getUserFacebookRedirectSeeOther
*/
type GetUserFacebookRedirectSeeOther struct {
	/*Redirect URL

	 */
	Location string `json:"Location"`
}

// NewGetUserFacebookRedirectSeeOther creates GetUserFacebookRedirectSeeOther with default headers values
func NewGetUserFacebookRedirectSeeOther() *GetUserFacebookRedirectSeeOther {

	return &GetUserFacebookRedirectSeeOther{}
}

// WithLocation adds the location to the get user facebook redirect see other response
func (o *GetUserFacebookRedirectSeeOther) WithLocation(location string) *GetUserFacebookRedirectSeeOther {
	o.Location = location
	return o
}

// SetLocation sets the location to the get user facebook redirect see other response
func (o *GetUserFacebookRedirectSeeOther) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *GetUserFacebookRedirectSeeOther) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(303)
}
