// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetUserGoogleRedirectParams creates a new GetUserGoogleRedirectParams object
// no default values defined in spec.
func NewGetUserGoogleRedirectParams() GetUserGoogleRedirectParams {

	return GetUserGoogleRedirectParams{}
}

// GetUserGoogleRedirectParams contains all the bound params for the get user google redirect operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetUserGoogleRedirect
type GetUserGoogleRedirectParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Work around for same-site cookie. Do not set
	  In: query
	*/
	Trampoline *string
	/*Authorization code from Google
	  Required: true
	  In: query
	*/
	Code string
	/*Nonce state from Google
	  Required: true
	  In: query
	*/
	State string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetUserGoogleRedirectParams() beforehand.
func (o *GetUserGoogleRedirectParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qTrampoline, qhkTrampoline, _ := qs.GetOK("__trampoline")
	if err := o.bindTrampoline(qTrampoline, qhkTrampoline, route.Formats); err != nil {
		res = append(res, err)
	}

	qCode, qhkCode, _ := qs.GetOK("code")
	if err := o.bindCode(qCode, qhkCode, route.Formats); err != nil {
		res = append(res, err)
	}

	qState, qhkState, _ := qs.GetOK("state")
	if err := o.bindState(qState, qhkState, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTrampoline binds and validates parameter Trampoline from query.
func (o *GetUserGoogleRedirectParams) bindTrampoline(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Trampoline = &raw

	return nil
}

// bindCode binds and validates parameter Code from query.
func (o *GetUserGoogleRedirectParams) bindCode(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("code", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("code", "query", raw); err != nil {
		return err
	}

	o.Code = raw

	return nil
}

// bindState binds and validates parameter State from query.
func (o *GetUserGoogleRedirectParams) bindState(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("state", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("state", "query", raw); err != nil {
		return err
	}

	o.State = raw

	return nil
}
