// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetMeetupIDHandlerFunc turns a function with the right signature into a get meetup ID handler
type GetMeetupIDHandlerFunc func(GetMeetupIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMeetupIDHandlerFunc) Handle(params GetMeetupIDParams) middleware.Responder {
	return fn(params)
}

// GetMeetupIDHandler interface for that can handle valid get meetup ID params
type GetMeetupIDHandler interface {
	Handle(GetMeetupIDParams) middleware.Responder
}

// NewGetMeetupID creates a new http.Handler for the get meetup ID operation
func NewGetMeetupID(ctx *middleware.Context, handler GetMeetupIDHandler) *GetMeetupID {
	return &GetMeetupID{Context: ctx, Handler: handler}
}

/*GetMeetupID swagger:route GET /meetup/{id} getMeetupId

Get the specified meetup's information

If the specified meetup does not exist, an error is returned

*/
type GetMeetupID struct {
	Context *middleware.Context
	Handler GetMeetupIDHandler
}

func (o *GetMeetupID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMeetupIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
