// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetUserFacebookRedirectSeeOtherCode is the HTTP code returned for type GetUserFacebookRedirectSeeOther
const GetUserFacebookRedirectSeeOtherCode int = 303

/*GetUserFacebookRedirectSeeOther Redirect to home page.

swagger:response getUserFacebookRedirectSeeOther
*/
type GetUserFacebookRedirectSeeOther struct {
	/*Redirect URL

	 */
	Location string `json:"Location"`
}

// NewGetUserFacebookRedirectSeeOther creates GetUserFacebookRedirectSeeOther with default headers values
func NewGetUserFacebookRedirectSeeOther() *GetUserFacebookRedirectSeeOther {

	return &GetUserFacebookRedirectSeeOther{}
}

// WithLocation adds the location to the get user facebook redirect see other response
func (o *GetUserFacebookRedirectSeeOther) WithLocation(location string) *GetUserFacebookRedirectSeeOther {
	o.Location = location
	return o
}

// SetLocation sets the location to the get user facebook redirect see other response
func (o *GetUserFacebookRedirectSeeOther) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *GetUserFacebookRedirectSeeOther) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(303)
}
