// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetUserGoogleRedirectOKCode is the HTTP code returned for type GetUserGoogleRedirectOK
const GetUserGoogleRedirectOKCode int = 200

/*GetUserGoogleRedirectOK Simple HTML file that will redirect user to the home page.

swagger:response getUserGoogleRedirectOK
*/
type GetUserGoogleRedirectOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetUserGoogleRedirectOK creates GetUserGoogleRedirectOK with default headers values
func NewGetUserGoogleRedirectOK() *GetUserGoogleRedirectOK {

	return &GetUserGoogleRedirectOK{}
}

// WithPayload adds the payload to the get user google redirect o k response
func (o *GetUserGoogleRedirectOK) WithPayload(payload string) *GetUserGoogleRedirectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user google redirect o k response
func (o *GetUserGoogleRedirectOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserGoogleRedirectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetUserGoogleRedirectSeeOtherCode is the HTTP code returned for type GetUserGoogleRedirectSeeOther
const GetUserGoogleRedirectSeeOtherCode int = 303

/*GetUserGoogleRedirectSeeOther Redirect to home page.

swagger:response getUserGoogleRedirectSeeOther
*/
type GetUserGoogleRedirectSeeOther struct {
	/*Redirect URL

	 */
	Location string `json:"Location"`
}

// NewGetUserGoogleRedirectSeeOther creates GetUserGoogleRedirectSeeOther with default headers values
func NewGetUserGoogleRedirectSeeOther() *GetUserGoogleRedirectSeeOther {

	return &GetUserGoogleRedirectSeeOther{}
}

// WithLocation adds the location to the get user google redirect see other response
func (o *GetUserGoogleRedirectSeeOther) WithLocation(location string) *GetUserGoogleRedirectSeeOther {
	o.Location = location
	return o
}

// SetLocation sets the location to the get user google redirect see other response
func (o *GetUserGoogleRedirectSeeOther) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *GetUserGoogleRedirectSeeOther) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(303)
}
