// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetUserFacebookAuthSeeOtherCode is the HTTP code returned for type GetUserFacebookAuthSeeOther
const GetUserFacebookAuthSeeOtherCode int = 303

/*GetUserFacebookAuthSeeOther Redirect to Facebook login prompt.

swagger:response getUserFacebookAuthSeeOther
*/
type GetUserFacebookAuthSeeOther struct {
	/*Redirect URL

	 */
	Location string `json:"Location"`
}

// NewGetUserFacebookAuthSeeOther creates GetUserFacebookAuthSeeOther with default headers values
func NewGetUserFacebookAuthSeeOther() *GetUserFacebookAuthSeeOther {

	return &GetUserFacebookAuthSeeOther{}
}

// WithLocation adds the location to the get user facebook auth see other response
func (o *GetUserFacebookAuthSeeOther) WithLocation(location string) *GetUserFacebookAuthSeeOther {
	o.Location = location
	return o
}

// SetLocation sets the location to the get user facebook auth see other response
func (o *GetUserFacebookAuthSeeOther) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *GetUserFacebookAuthSeeOther) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(303)
}
