// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetUserGoogleAuthSeeOtherCode is the HTTP code returned for type GetUserGoogleAuthSeeOther
const GetUserGoogleAuthSeeOtherCode int = 303

/*GetUserGoogleAuthSeeOther Redirect to Google login prompt.

swagger:response getUserGoogleAuthSeeOther
*/
type GetUserGoogleAuthSeeOther struct {
	/*Redirect URL

	 */
	Location string `json:"Location"`
}

// NewGetUserGoogleAuthSeeOther creates GetUserGoogleAuthSeeOther with default headers values
func NewGetUserGoogleAuthSeeOther() *GetUserGoogleAuthSeeOther {

	return &GetUserGoogleAuthSeeOther{}
}

// WithLocation adds the location to the get user google auth see other response
func (o *GetUserGoogleAuthSeeOther) WithLocation(location string) *GetUserGoogleAuthSeeOther {
	o.Location = location
	return o
}

// SetLocation sets the location to the get user google auth see other response
func (o *GetUserGoogleAuthSeeOther) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *GetUserGoogleAuthSeeOther) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(303)
}
