// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetUserFacebookRedirectParams creates a new GetUserFacebookRedirectParams object
// no default values defined in spec.
func NewGetUserFacebookRedirectParams() GetUserFacebookRedirectParams {

	return GetUserFacebookRedirectParams{}
}

// GetUserFacebookRedirectParams contains all the bound params for the get user facebook redirect operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetUserFacebookRedirect
type GetUserFacebookRedirectParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Authorization code from Facebook
	  In: query
	*/
	Code *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetUserFacebookRedirectParams() beforehand.
func (o *GetUserFacebookRedirectParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qCode, qhkCode, _ := qs.GetOK("code")
	if err := o.bindCode(qCode, qhkCode, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCode binds and validates parameter Code from query.
func (o *GetUserFacebookRedirectParams) bindCode(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Code = &raw

	return nil
}
