// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetSetCookieOKCode is the HTTP code returned for type GetSetCookieOK
const GetSetCookieOKCode int = 200

/*GetSetCookieOK OK

swagger:response getSetCookieOK
*/
type GetSetCookieOK struct {
	/*

	 */
	SetCookie string `json:"Set-Cookie"`

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetSetCookieOK creates GetSetCookieOK with default headers values
func NewGetSetCookieOK() *GetSetCookieOK {

	return &GetSetCookieOK{}
}

// WithSetCookie adds the setCookie to the get set cookie o k response
func (o *GetSetCookieOK) WithSetCookie(setCookie string) *GetSetCookieOK {
	o.SetCookie = setCookie
	return o
}

// SetSetCookie sets the setCookie to the get set cookie o k response
func (o *GetSetCookieOK) SetSetCookie(setCookie string) {
	o.SetCookie = setCookie
}

// WithPayload adds the payload to the get set cookie o k response
func (o *GetSetCookieOK) WithPayload(payload string) *GetSetCookieOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get set cookie o k response
func (o *GetSetCookieOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSetCookieOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Set-Cookie

	setCookie := o.SetCookie
	if setCookie != "" {
		rw.Header().Set("Set-Cookie", setCookie)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
