// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetMeetupIDAttendeeHandlerFunc turns a function with the right signature into a get meetup ID attendee handler
type GetMeetupIDAttendeeHandlerFunc func(GetMeetupIDAttendeeParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMeetupIDAttendeeHandlerFunc) Handle(params GetMeetupIDAttendeeParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetMeetupIDAttendeeHandler interface for that can handle valid get meetup ID attendee params
type GetMeetupIDAttendeeHandler interface {
	Handle(GetMeetupIDAttendeeParams, interface{}) middleware.Responder
}

// NewGetMeetupIDAttendee creates a new http.Handler for the get meetup ID attendee operation
func NewGetMeetupIDAttendee(ctx *middleware.Context, handler GetMeetupIDAttendeeHandler) *GetMeetupIDAttendee {
	return &GetMeetupIDAttendee{Context: ctx, Handler: handler}
}

/*GetMeetupIDAttendee swagger:route GET /meetup/{id}/attendee getMeetupIdAttendee

Get list of attending and pending attendees for a specified meetup

If the specified meetup does not exist, an error is returned

*/
type GetMeetupIDAttendee struct {
	Context *middleware.Context
	Handler GetMeetupIDAttendeeHandler
}

func (o *GetMeetupIDAttendee) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMeetupIDAttendeeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
