// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetSetCookieParams creates a new GetSetCookieParams object
// no default values defined in spec.
func NewGetSetCookieParams() GetSetCookieParams {

	return GetSetCookieParams{}
}

// GetSetCookieParams contains all the bound params for the get set cookie operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetSetCookie
type GetSetCookieParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*User ID to set
	  In: query
	*/
	UserID *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetSetCookieParams() beforehand.
func (o *GetSetCookieParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qUserID, qhkUserID, _ := qs.GetOK("user_id")
	if err := o.bindUserID(qUserID, qhkUserID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindUserID binds and validates parameter UserID from query.
func (o *GetSetCookieParams) bindUserID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.UserID = &raw

	return nil
}
