// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"go.timothygu.me/downtomeet/server/models"
)

// GetMeetupOKCode is the HTTP code returned for type GetMeetupOK
const GetMeetupOKCode int = 200

/*GetMeetupOK OK

swagger:response getMeetupOK
*/
type GetMeetupOK struct {

	/*
	  In: Body
	*/
	Payload []models.MeetupID `json:"body,omitempty"`
}

// NewGetMeetupOK creates GetMeetupOK with default headers values
func NewGetMeetupOK() *GetMeetupOK {

	return &GetMeetupOK{}
}

// WithPayload adds the payload to the get meetup o k response
func (o *GetMeetupOK) WithPayload(payload []models.MeetupID) *GetMeetupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get meetup o k response
func (o *GetMeetupOK) SetPayload(payload []models.MeetupID) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeetupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]models.MeetupID, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetMeetupBadRequestCode is the HTTP code returned for type GetMeetupBadRequest
const GetMeetupBadRequestCode int = 400

/*GetMeetupBadRequest Bad Request

swagger:response getMeetupBadRequest
*/
type GetMeetupBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMeetupBadRequest creates GetMeetupBadRequest with default headers values
func NewGetMeetupBadRequest() *GetMeetupBadRequest {

	return &GetMeetupBadRequest{}
}

// WithPayload adds the payload to the get meetup bad request response
func (o *GetMeetupBadRequest) WithPayload(payload *models.Error) *GetMeetupBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get meetup bad request response
func (o *GetMeetupBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeetupBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetMeetupInternalServerErrorCode is the HTTP code returned for type GetMeetupInternalServerError
const GetMeetupInternalServerErrorCode int = 500

/*GetMeetupInternalServerError Internal server error

swagger:response getMeetupInternalServerError
*/
type GetMeetupInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMeetupInternalServerError creates GetMeetupInternalServerError with default headers values
func NewGetMeetupInternalServerError() *GetMeetupInternalServerError {

	return &GetMeetupInternalServerError{}
}

// WithPayload adds the payload to the get meetup internal server error response
func (o *GetMeetupInternalServerError) WithPayload(payload *models.Error) *GetMeetupInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get meetup internal server error response
func (o *GetMeetupInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeetupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
