// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"go.timothygu.me/downtomeet/server/models"
)

// GetMeetupIDOKCode is the HTTP code returned for type GetMeetupIDOK
const GetMeetupIDOKCode int = 200

/*GetMeetupIDOK OK

swagger:response getMeetupIdOK
*/
type GetMeetupIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Meetup `json:"body,omitempty"`
}

// NewGetMeetupIDOK creates GetMeetupIDOK with default headers values
func NewGetMeetupIDOK() *GetMeetupIDOK {

	return &GetMeetupIDOK{}
}

// WithPayload adds the payload to the get meetup Id o k response
func (o *GetMeetupIDOK) WithPayload(payload *models.Meetup) *GetMeetupIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get meetup Id o k response
func (o *GetMeetupIDOK) SetPayload(payload *models.Meetup) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeetupIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetMeetupIDBadRequestCode is the HTTP code returned for type GetMeetupIDBadRequest
const GetMeetupIDBadRequestCode int = 400

/*GetMeetupIDBadRequest Bad Request

swagger:response getMeetupIdBadRequest
*/
type GetMeetupIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMeetupIDBadRequest creates GetMeetupIDBadRequest with default headers values
func NewGetMeetupIDBadRequest() *GetMeetupIDBadRequest {

	return &GetMeetupIDBadRequest{}
}

// WithPayload adds the payload to the get meetup Id bad request response
func (o *GetMeetupIDBadRequest) WithPayload(payload *models.Error) *GetMeetupIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get meetup Id bad request response
func (o *GetMeetupIDBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeetupIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetMeetupIDNotFoundCode is the HTTP code returned for type GetMeetupIDNotFound
const GetMeetupIDNotFoundCode int = 404

/*GetMeetupIDNotFound Not found

swagger:response getMeetupIdNotFound
*/
type GetMeetupIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMeetupIDNotFound creates GetMeetupIDNotFound with default headers values
func NewGetMeetupIDNotFound() *GetMeetupIDNotFound {

	return &GetMeetupIDNotFound{}
}

// WithPayload adds the payload to the get meetup Id not found response
func (o *GetMeetupIDNotFound) WithPayload(payload *models.Error) *GetMeetupIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get meetup Id not found response
func (o *GetMeetupIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeetupIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
