// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchMeetupIDHandlerFunc turns a function with the right signature into a patch meetup ID handler
type PatchMeetupIDHandlerFunc func(PatchMeetupIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchMeetupIDHandlerFunc) Handle(params PatchMeetupIDParams) middleware.Responder {
	return fn(params)
}

// PatchMeetupIDHandler interface for that can handle valid patch meetup ID params
type PatchMeetupIDHandler interface {
	Handle(PatchMeetupIDParams) middleware.Responder
}

// NewPatchMeetupID creates a new http.Handler for the patch meetup ID operation
func NewPatchMeetupID(ctx *middleware.Context, handler PatchMeetupIDHandler) *PatchMeetupID {
	return &PatchMeetupID{Context: ctx, Handler: handler}
}

/*PatchMeetupID swagger:route PATCH /meetup/{id} patchMeetupId

Patch the specified meetup

*/
type PatchMeetupID struct {
	Context *middleware.Context
	Handler PatchMeetupIDHandler
}

func (o *PatchMeetupID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchMeetupIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
