// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchMeetupIDAttendeeHandlerFunc turns a function with the right signature into a patch meetup ID attendee handler
type PatchMeetupIDAttendeeHandlerFunc func(PatchMeetupIDAttendeeParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchMeetupIDAttendeeHandlerFunc) Handle(params PatchMeetupIDAttendeeParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PatchMeetupIDAttendeeHandler interface for that can handle valid patch meetup ID attendee params
type PatchMeetupIDAttendeeHandler interface {
	Handle(PatchMeetupIDAttendeeParams, interface{}) middleware.Responder
}

// NewPatchMeetupIDAttendee creates a new http.Handler for the patch meetup ID attendee operation
func NewPatchMeetupIDAttendee(ctx *middleware.Context, handler PatchMeetupIDAttendeeHandler) *PatchMeetupIDAttendee {
	return &PatchMeetupIDAttendee{Context: ctx, Handler: handler}
}

/*PatchMeetupIDAttendee swagger:route PATCH /meetup/{id}/attendee patchMeetupIdAttendee

Patch the current user's attendee status for the specified meetup

If the specified meetup does not exist, an error is returned

*/
type PatchMeetupIDAttendee struct {
	Context *middleware.Context
	Handler PatchMeetupIDAttendeeHandler
}

func (o *PatchMeetupIDAttendee) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchMeetupIDAttendeeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
