// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostMeetupHandlerFunc turns a function with the right signature into a post meetup handler
type PostMeetupHandlerFunc func(PostMeetupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostMeetupHandlerFunc) Handle(params PostMeetupParams) middleware.Responder {
	return fn(params)
}

// PostMeetupHandler interface for that can handle valid post meetup params
type PostMeetupHandler interface {
	Handle(PostMeetupParams) middleware.Responder
}

// NewPostMeetup creates a new http.Handler for the post meetup operation
func NewPostMeetup(ctx *middleware.Context, handler PostMeetupHandler) *PostMeetup {
	return &PostMeetup{Context: ctx, Handler: handler}
}

/*PostMeetup swagger:route POST /meetup postMeetup

Post a new meetup

*/
type PostMeetup struct {
	Context *middleware.Context
	Handler PostMeetupHandler
}

func (o *PostMeetup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostMeetupParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
