// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"go.timothygu.me/downtomeet/server/models"
)

// NewPostMeetupParams creates a new PostMeetupParams object
// no default values defined in spec.
func NewPostMeetupParams() PostMeetupParams {

	return PostMeetupParams{}
}

// PostMeetupParams contains all the bound params for the post meetup operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostMeetup
type PostMeetupParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The meetup to create
	  In: body
	*/
	Meetup *models.MeetupRequestBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostMeetupParams() beforehand.
func (o *PostMeetupParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.MeetupRequestBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("meetup", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Meetup = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
