export const SERVER_URL = "http://localhost:9000";

export const IN_PERSON = "in-person";
export const REMOTE = "remote";

export const OWNER = "owner";
export const ATTENDING = "attending";
export const PENDING = "pending";
export const REJECTED = "rejected";
export const NONE = "none";

export const tagOptions = [
  "3d printing",
  "43-man squamish",
  "5x5x5",
  "6x6x6",
  "7x7x7",
  "Adopt Me!",
  "Animal Jam",
  "Apex Legends",
  "Ark: Survival Evolved",
  "Battlefield 4",
  "Black Desert Online",
  "Blade & Soul",
  "Call of Duty: Ghosts",
  "Call of Duty: WWII",
  "Call of Duty: Warzone",
  "Candy Crush Saga",
  "CityVille",
  "Counter-Strike: Global Offensive",
  "Crazyracing Kartrider",
  "CrossFire",
  "DC Universe Online",
  "Dofus",
  "Doom",
  "Dota 2",
  "Dragon Nest",
  "Dragon Oath",
  "Drakensang Online",
  "Dungeon Fighter Online (DFO)",
  "Evony",
  "FIFA 16",
  "FIFA 17",
  "FIFA 18",
  "FIFA 19",
  "Fantasy Westward Journey",
  "Farm Town",
  "FarmVille 2",
  "FarmVille",
  "Final Fantasy XIV",
  "Flyff",
  "For Honor",
  "Fortnite",
  "Forza Horizon 3",
  "Free Realms",
  "GetAmped",
  "Grand Theft Auto V",
  "Guild Wars 2",
  "H1Z1",
  "Happy Farm",
  "Hearthstone",
  "Honor of Kings",
  "League of Legends",
  "Left 4 Dead 2",
  "Lineage II",
  "Lineage",
  "Mabinogi",
  "MapleStory",
  "Metal Slug Defense",
  "Microsoft Solitaire Collection",
  "Microsoft Solitaire",
  "Minecraft",
  "Mini World",
  "Moshi Monsters",
  "Nexus: The Kingdom of the Winds",
  "Overwatch",
  "Pac-Man Doodle",
  "Pac-Man",
  "Paladins",
  "Payday 2",
  "Perfect World",
  "PlayerUnknown's Battlegrounds (PUBG)",
  "Puyopuyo!! Quest Arcade",
  "QQ Speed",
  "Ragnarok Online",
  "Roblox",
  "Robocraft",
  "Rocket League",
  "Rules of Survival",
  "RuneScape",
  "Scions of Fate",
  "Shadowverse",
  "Star Wars: The Old Republic",
  "Street Fighter II",
  "Sudden Attack",
  "TERA",
  "Team Fortress 2",
  "Teamfight Tactics",
  "Tetris",
  "The Elder Scrolls Online",
  "The Last of Us Remastered",
  "The Legend of Mir 3",
  "The Sims Social",
  "Tom Clancy's Rainbow Six Siege",
  "Trove",
  "Unturned",
  "Warframe",
  "Westward Journey Online II",
  "World of Tanks",
  "World of Warcraft",
  "Yu-Gi-Oh! Duel Links",
  "Zhengtu",
  "acapella",
  "aerial silks",
  "air guns",
  "air sports",
  "airsoft",
  "amerigame",
  "animation",
  "antiquing",
  "archery",
  "art",
  "artistic pool",
  "astronomy",
  "australian football",
  "badminton",
  "baking",
  "balloon twisting",
  "ballroom dancing",
  "barrel racing",
  "base jumping",
  "baseball",
  "basketball",
  "baton twirling",
  "beatboxing",
  "beekeeping",
  "beer pong",
  "bicycle polo",
  "bird watching",
  "blacksmithing",
  "blogging ",
  "bmx",
  "board games",
  "board sports",
  "boardercross",
  "bodybuilding",
  "boli khela",
  "book club ",
  "book restoration",
  "bouldering",
  "break dancing",
  "british bulldogs",
  "bronc riding",
  "bullriding",
  "cabaret",
  "calf roping",
  "calligraphy",
  "calvinball",
  "camping",
  "candle making",
  "canoeing",
  "canyon exploration",
  "card games",
  "carrom boards",
  "cartooning",
  "casterboarding",
  "checkers",
  "chess boxing",
  "chess960",
  "chun kuk do",
  "cirit",
  "cliff diving",
  "clowning",
  "coastal and ocean rowing",
  "collecting",
  "coloring",
  "combat robot",
  "community theatre",
  "competitive dancing",
  "competitive eating",
  "competitive swimming",
  "composite rules shinty-hurling",
  "computer programming",
  "concert going ",
  "cooking",
  "cooperative games",
  "couponing",
  "cowboy",
  "creative writing",
  "crocheting",
  "cross country",
  "cross-country rally",
  "cross-country running",
  "crossword puzzles",
  "cup stacking",
  "curling",
  "dance",
  "darts",
  "debating",
  "deck building games",
  "dice games",
  "disc golf (urban)",
  "distilling",
  "diving",
  "diy",
  "dodge disc",
  "dog showing",
  "double disc court",
  "drawing",
  "driving",
  "drone flying",
  "egg and spoon race",
  "egyptian stick fencing",
  "embroidery",
  "engraving",
  "eskrima",
  "eurogames",
  "f1 powerboat racing",
  "farming",
  "fast-pitch softball",
  "fastnet",
  "ferret legging",
  "film making",
  "fire poi",
  "fishkeeping",
  "five-pins",
  "flag football ",
  "flea market shopping",
  "flight archery",
  "flipping",
  "flower arranging",
  "flower pressing",
  "flutterguts",
  "flying aircraft",
  "flying disc games",
  "flying discs",
  "foosball",
  "footbag",
  "foraging",
  "fossil hunting",
  "fostering animals",
  "fourwheeling",
  "free running",
  "free-style moto",
  "freeboating",
  "freestyle motocross",
  "freestyle snowboarding",
  "games",
  "gardening/herb growing",
  "geocaching",
  "ghost-hunting",
  "gig racing",
  "glassblowing",
  "go",
  "go-moku",
  "goal (sport)",
  "goat tying",
  "gold prospecting",
  "graffiti",
  "gungdo",
  "guyball",
  "gymnastics",
  "handball",
  "hangzhou, china",
  "hide and seek",
  "hiking",
  "historical reenactment",
  "homebrewing",
  "hookah",
  "hooping",
  "horse polo",
  "horseback riding",
  "hot air ballooning",
  "human powered aircraft",
  "hurdles",
  "iaidō",
  "ice dancing",
  "ice fishing",
  "ice sledge",
  "ice yachting",
  "ice-skating",
  "iditarod",
  "improv acting",
  "indoor archery",
  "indoor enduro",
  "indoor field hockey",
  "inline hockey",
  "inline skating",
  "interior decorating",
  "jet sprint boat racing",
  "jewelry making",
  "jigsaw puzzles",
  "jiu-jitsu",
  "jogging",
  "journaling",
  "juggling ",
  "kayaking",
  "ki-o-rahi",
  "kite fighting",
  "kite flying",
  "kiteboarding",
  "kitesurfing",
  "kneeboarding",
  "knitting",
  "lace making",
  "lacrosse",
  "lagori",
  "land speed records",
  "larping",
  "lego building",
  "letterboxing",
  "longboarding",
  "macrame",
  "magic the gathering",
  "magic",
  "marathons",
  "martial arts",
  "massage",
  "meditation ",
  "metal detecting",
  "metro footy",
  "mind sports",
  "miniature games",
  "mob football",
  "model engineering/building",
  "moose biathon",
  "motocross",
  "motor sports ",
  "mountain biking",
  "mountaineering",
  "movie",
  "museum hopping ",
  "needlepoint",
  "netball",
  "ninja warrior",
  "nordic skating",
  "offroading",
  "oina",
  "one-cushion carom",
  "orienteering",
  "origami",
  "osu!",
  "outline of kayaking and canoeing",
  "outrigger canoeing",
  "oztag",
  "paintball",
  "painting",
  "pak hyon-suk",
  "pall mall",
  "palm reading",
  "paramotoring",
  "parkour",
  "pencak silat",
  "pencil-and-paper games",
  "personal water craft",
  "photography",
  "ping pong",
  "pioneerball",
  "playing guitar",
  "playing in a band",
  "podcasting",
  "pokemon",
  "pole dancing",
  "polo",
  "pool",
  "pottery",
  "powerbocking",
  "powerlifting",
  "precision rifle competition",
  "pyrotechnics",
  "quidditch",
  "quilling",
  "quilting",
  "quizzing",
  "racquets",
  "rafting",
  "rappelling",
  "rapping",
  "red rover",
  "refinishing furniture",
  "renaissance fairs",
  "rink hockey",
  "rinkball",
  "roadtripping",
  "robot combat",
  "rock climbing",
  "rock painting",
  "role-playing games",
  "roleplaying",
  "rollball",
  "roller hockey (quad)",
  "roller skating",
  "rope jumping",
  "roping",
  "rowing",
  "rugby",
  "running",
  "saddle bronc riding",
  "sailing/boating",
  "salsa dancing",
  "sand art ",
  "sanshou",
  "scarpbooking",
  "scouting",
  "scuba diving",
  "sculping",
  "sea kayaking",
  "self defense",
  "shinty–hurling",
  "sholo guti",
  "shooting/hunting/fishing",
  "short track motor racing",
  "singing",
  "sipa",
  "skateboarding",
  "skater hockey",
  "skee ball",
  "skibob",
  "skiing",
  "skydiving",
  "slacklining",
  "smoking meat/grilling",
  "snooker plus",
  "snorkelling",
  "snow kiting",
  "snowboarding",
  "snowmobiling",
  "soap shoes",
  "soapmaking",
  "softball",
  "sogo",
  "sport fishing",
  "sports",
  "stand up paddle boarding",
  "stand-up comedy",
  "star gazing",
  "steer wrestling",
  "stone skipping",
  "stool ball",
  "storm chasing",
  "strategy games",
  "streetboarding",
  "streetluge",
  "sudoku",
  "summer biathlon",
  "supercross",
  "supersport racing",
  "surfing",
  "swimming",
  "sword fighting",
  "t'ai chi ch'uan",
  "table tennis",
  "tabletop games",
  "taekwondo",
  "tag games",
  "tai chi",
  "target sprint",
  "tarot reading",
  "tatooing",
  "taxidermy",
  "team roping",
  "thumb wrestling",
  "tile-based games",
  "tombstone rubbing",
  "topiary",
  "touch football",
  "tower running",
  "travel",
  "trivia",
  "tug-o-war",
  "unicycle basketball",
  "unicycling",
  "upcycling",
  "urban exploration",
  "varzesh-e pahlavani",
  "vehicle restoration",
  "video editing",
  "video games",
  "video gaming",
  "vlogging",
  "volunteer firefighting",
  "water sports",
  "waterpolo",
  "waymarking",
  "whale watching",
  "whittling",
  "wiffleball",
  "wine-making",
  "wizards the happening",
  "wood chopping",
  "woodworking",
  "writing",
  "xare",
  "yağlı güreş",
  "yo-yoing",
  "yoga",
  "yoyoing",
  "zourkhaneh",
  "zumba",
];
