// Code generated by "stringer -type=contextKey"; DO NOT EDIT.

package impl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[contextSession-0]
}

const _contextKey_name = "contextSession"

var _contextKey_index = [...]uint8{0, 14}

func (i contextKey) String() string {
	if i < 0 || i >= contextKey(len(_contextKey_index)-1) {
		return "contextKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _contextKey_name[_contextKey_index[i]:_contextKey_index[i+1]]
}
