// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AttendeeList attendee list
//
// swagger:model attendeeList
type AttendeeList struct {

	// attending
	Attending []UserID `json:"attending"`

	// pending
	Pending []UserID `json:"pending"`
}

// Validate validates this attendee list
func (m *AttendeeList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttending(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePending(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AttendeeList) validateAttending(formats strfmt.Registry) error {

	if swag.IsZero(m.Attending) { // not required
		return nil
	}

	for i := 0; i < len(m.Attending); i++ {

		if err := m.Attending[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("attending" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (m *AttendeeList) validatePending(formats strfmt.Registry) error {

	if swag.IsZero(m.Pending) { // not required
		return nil
	}

	for i := 0; i < len(m.Pending); i++ {

		if err := m.Pending[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pending" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AttendeeList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AttendeeList) UnmarshalBinary(b []byte) error {
	var res AttendeeList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
