// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Location location
//
// swagger:model location
type Location struct {

	// lat
	// Maximum: 90
	// Minimum: -90
	Lat *float64 `json:"lat,omitempty"`

	// lon
	// Maximum: 180
	// Minimum: -180
	Lon *float64 `json:"lon,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this location
func (m *Location) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLon(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Location) validateLat(formats strfmt.Registry) error {

	if swag.IsZero(m.Lat) { // not required
		return nil
	}

	if err := validate.Minimum("lat", "body", float64(*m.Lat), -90, false); err != nil {
		return err
	}

	if err := validate.Maximum("lat", "body", float64(*m.Lat), 90, false); err != nil {
		return err
	}

	return nil
}

func (m *Location) validateLon(formats strfmt.Registry) error {

	if swag.IsZero(m.Lon) { // not required
		return nil
	}

	if err := validate.Minimum("lon", "body", float64(*m.Lon), -180, false); err != nil {
		return err
	}

	if err := validate.Maximum("lon", "body", float64(*m.Lon), 180, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Location) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Location) UnmarshalBinary(b []byte) error {
	var res Location
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
