// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MeetupRequestBody meetup request body
//
// swagger:model meetupRequestBody
type MeetupRequestBody struct {

	// location
	Location *Location `json:"location,omitempty"`

	// max capacity
	MaxCapacity int64 `json:"maxCapacity,omitempty"`

	// min capacity
	// Minimum: 0
	MinCapacity *int64 `json:"minCapacity,omitempty"`

	// tags
	Tags []string `json:"tags"`

	// time
	Time string `json:"time,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this meetup request body
func (m *MeetupRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLocation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMinCapacity(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MeetupRequestBody) validateLocation(formats strfmt.Registry) error {

	if swag.IsZero(m.Location) { // not required
		return nil
	}

	if m.Location != nil {
		if err := m.Location.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("location")
			}
			return err
		}
	}

	return nil
}

func (m *MeetupRequestBody) validateMinCapacity(formats strfmt.Registry) error {

	if swag.IsZero(m.MinCapacity) { // not required
		return nil
	}

	if err := validate.MinimumInt("minCapacity", "body", int64(*m.MinCapacity), 0, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MeetupRequestBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MeetupRequestBody) UnmarshalBinary(b []byte) error {
	var res MeetupRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
