// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// TagID tag ID
//
// swagger:model tagID
type TagID string

// Validate validates this tag ID
func (m TagID) Validate(formats strfmt.Registry) error {
	return nil
}
