// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// UserID user ID
//
// swagger:model userID
type UserID string

// Validate validates this user ID
func (m UserID) Validate(formats strfmt.Registry) error {
	return nil
}
