---
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

on: push

jobs:
  eslint:
    name: Lint JavaScript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Yarn install
        run: cd client && yarn --frozen-lockfile

      - name: Lint JavaScript
        run: cd client && yarn lint
  
  testgo:
    name: Test Go Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      
      - run: go mod download

      - run: go vet ./...

      - run: go test ./...

      - name: Format code
        run: |
          make -C server format
          if ! git diff --exit-code; then
            echo 'Code not formatted correctly; run make -C server format'
            exit 1
          fi

      - name: Regenerate boilerplate code
        run: |
          make -C server generate
          if ! git diff --exit-code; then
            echo 'Generated code not up to date; run make -C server generate'
            exit 1
          fi

      - name: Run go mod tidy
        run: |
          go mod tidy
          if ! git diff --exit-code; then
            echo 'Dependencies not up to date; run go mod tidy'
            exit 1
          fi
